### ISSUE TITLE
No GetAddonInfos on Fritz!Box 6490 (lgi branded)

### ISSUE THREAD

**Issue by codmpm** [bashGroup/node-red-contrib-fritz#1]
Hi,

first I want to thank you for your work. Right now I'm building my home automation based on node-red, coming from openhab.

At the moment I still have the branded Fritz!Box 6490 from Unitymedia and want to get the current used bandwith. When available I will switch to the 6580 to finally get the full potential out of my router. 

From everything I read, one needs the `GetAddonInfos`-action to get `NewByteSendRate` which should be the "current bandwith send rate". On discovery`WANCommonInterfaceConfig` there is no action called `GetAddonInfos`. So I've tried to set the desired action via `msg.action`:

![bildschirmfoto 2016-09-25 um 19 08 41](https://cloud.githubusercontent.com/assets/9745239/18816932/ef853956-8353-11e6-9346-19072fd1abb6.png)

But sadly I get this error:
`TypeError: node.config.device.services[service].actions[action] is not a function`

Could you give me a hint if the error is on my side? Did I miss something?

Maybe this is simply not possible with the lgi-branded Fritz!Box. I'm running Fritz!Os 6.50.

Cheers,
Patrik

**Comment by codmpm** [comment]
I've just installend FritzBoxTrafficSetup-64bit-1.11.94.msi from http://www.bawe.eu/cms/Projekte.html in a Windows VM an to my surprise it can get the current bandwith from the 6490. 

Maybe you can give me a hint in the right direction.

Cheers,
Patrik

**Comment by mapero** [comment]
Hi Patrik,

thanks for your feedback. The reason why `WANCommonInterfaceConfig` is not working at the moment is, that some services are handled differently in the lib [hendrikw01/tr-064](https://github.com/hendrikw01/tr-064) I used. You can access the services as IGD (Internet Gateway Device) or TR064 device which results in different services provided. I did only implement the tr064 at the moment. There are two possibilities:

a) I add the igd service to the current node
b) I add a second node to the collection

I will look into it, but I will not have time until mid of October. If you can't wait you are free to provide a pull request :). It should not be to hard to implement.

Cheers,
Jochen

**Comment by codmpm** [comment]
Hi Jochen,

thank you for your answer. Meanwhile I could at least prove that it works with my branded Fritz!Box 6490:

```
#!/usr/bin/php
<?php

$client = new SoapClient(
    null,
    array(
        'location' => "http://fritz.box:49000/igdupnp/control/WANCommonIFC1",
        'uri' => "urn:schemas-upnp-org:service:WANCommonInterfaceConfig:1",
        'noroot' => true
    )
);

echo json_encode($client->GetAddonInfos());
```
_Idea taken from http://www.bitmania.de/index.php?page=194_

As I'm fairly good with javascript node.js and TR-064 especially are new for me. When I find time to dive into it I would be glad to submit a PR - but don't count on me ;-)
It is a long time plan from me to get to know node.js to write own node-red-nodes.

Thank you very much!

Cheers,
Patrik

**Comment by mapero** [comment]
@codmpm Can you check it again?

**Comment by codmpm** [comment]
Works with choosing IGD in node: 

`[{"id":"54b5c687.aed5c8","type":"fritzbox-in","z":"31280dc9.8fdbaa","device":"178df84d.71363","name":"","provider":"IGD","service":"urn:schemas-upnp-org:service:WANCommonInterfaceConfig:1","action":"GetAddonInfos","arguments":"{}","x":270,"y":3000,"wires":[["fe9b7836.aeb3e8"]]},{"id":"fe9b7836.aeb3e8","type":"debug","z":"31280dc9.8fdbaa","name":"","active":true,"console":"false","complete":"false","x":440,"y":3000,"wires":[]},{"id":"c37499a6.332728","type":"inject","z":"31280dc9.8fdbaa","name":"","topic":"","payload":"","payloadType":"date","repeat":"","crontab":"","once":false,"x":100,"y":3000,"wires":[["54b5c687.aed5c8"]]},{"id":"178df84d.71363","type":"fritzbox-config","z":"31280dc9.8fdbaa","name":"my fritz","host":"fritz.box"}]`

Didn't try passing `msg.provider` and `msg.service` though.

Great work, thank you!!
