### ISSUE TITLE
Socket leakage on flow redeploy

### ISSUE THREAD

**Issue by samuelvetsch** [bashGroup/node-red-contrib-fritz#11]
Hi,
Thanks for your fritzbox contribution.
I have a small issue when a redeploy flows using callmonitor.
It seams that socket are not released properly:
After 20 flow redeploys, I can see my used sockets:

root@domotic:~# netstat | grep 1012
tcp        0      0 domotic.fritz.box:60109 fritz.box:1012          ESTABLISHED
tcp        0      0 domotic.fritz.box:60500 fritz.box:1012          ESTABLISHED
tcp        0      0 domotic.fritz.box:60919 fritz.box:1012          ESTABLISHED
tcp        0      0 domotic.fritz.box:60822 fritz.box:1012          ESTABLISHED
tcp        0      0 domotic.fritz.box:60569 fritz.box:1012          ESTABLISHED
tcp        0      0 domotic.fritz.box:60366 fritz.box:1012          ESTABLISHED
tcp        0      0 domotic.fritz.box:60028 fritz.box:1012          ESTABLISHED
tcp        0      0 domotic.fritz.box:60715 fritz.box:1012          ESTABLISHED
tcp        0      0 domotic.fritz.box:60269 fritz.box:1012          ESTABLISHED
tcp        0      0 domotic.fritz.box:60176 fritz.box:1012          ESTABLISHED
tcp        0      0 domotic.fritz.box:60431 fritz.box:1012          ESTABLISHED
tcp        0      0 domotic.fritz.box:60988 fritz.box:1012          ESTABLISHED
tcp        0      0 domotic.fritz.box:59751 fritz.box:1012          ESTABLISHED
tcp        0      0 domotic.fritz.box:59682 fritz.box:1012          ESTABLISHED
tcp        0      0 domotic.fritz.box:59816 fritz.box:1012          ESTABLISHED
tcp        0      0 domotic.fritz.box:32824 fritz.box:1012          ESTABLISHED
tcp        0      0 domotic.fritz.box:59585 fritz.box:1012          ESTABLISHED
tcp        0      0 domotic.fritz.box:58671 fritz.box:1012          ESTABLISHED
tcp        0      0 domotic.fritz.box:60634 fritz.box:1012          ESTABLISHED
tcp        0      0 domotic.fritz.box:59935 fritz.box:1012          ESTABLISHED

And the callmonitor node states 'Disconnected'.
When I restart node-red, everything is fixed as soon as my sockets are released.

root@domotic:~# netstat | grep 1012
tcp        0      0 domotic.fritz.box:33010 fritz.box:1012          ESTABLISHED

And my callmonitor status is 'Connected' again.

I'm using:
17 Feb 23:03:17 - [info] Node-RED version: v0.18.3
17 Feb 23:03:17 - [info] Node.js  version: v9.4.0
17 Feb 23:03:17 - [info] Linux 3.2.0-4-amd64 x64 LE

**Comment by henrikekblad** [comment]
Same issue for me! Thought I was going crazy when seeing the same...

**Comment by mapero** [comment]
Not sure if I can do anything regarding the issue. I close the socket on every redeployment. Maybe a bug in the node? Does it happen with latest version of node, node-red and node-red-contrib-fritz

**Comment by mapero** [comment]
Since no more feedback. Closed
