### ISSUE TITLE
FRITZ!Box with only password

### ISSUE THREAD

**Issue by averlon** [bashGroup/node-red-contrib-fritz#127]
The FRITZ!Box-node has in his description the hint:
```
Hint: If you have set your fritzbox to login with "password only" you have to choose a random username that does not exist on the fritzbox, e.g. "admin" or "doesnotexist".
```
I have tried this but then I get the error:
```
Action failed with error: 401: Unauthorized
```
So I have to use the user that is setup, even if "password only" is set.

You probably please could update the hint!

**Comment by mapero** [comment]
I'll try to update the nodes in october and resolve the issue with #64
