### ISSUE TITLE
Support numbers without region

### ISSUE THREAD

**Issue by averlon** [bashGroup/node-red-contrib-fritz#128]
This message comes with a "FRITZ!Box Phonebook lookup":
```
The provided number xxx is not valid for region DE
``` 
Where xxx is one of my phone numbers (without area code).

Could you give me a hint where this message is initiated or what I probably have configured the wrong way!?

**Comment by mapero** [comment]
To allow phonebook lookup to work it needs normalized phone numbers. Currently phone numbers without area code are not supported and will most likely not be supported.

To fix that, you need to add the area code in your phonebook accordingly.

**Comment by averlon** [comment]
mmh - I checked all numbers in the phonebook of my FRITZ!Box. None of them is without area code.
Some with +xx (), some +xx 0000 - without ().

My own phone numbers are setup in the FRITZ!Box without area code - as it has to be. And the phone number listed in the message is one of my own phone numbers.

So I doubt, this message comes from numbers out of my phonebook numbers!

**Comment by averlon** [comment]
Einige Details:
Der Flow besteht aus "FRITZ!Box Callmonitor" nach "FRITZ!Box Phonebook lookup".

Dieser eingehende Ruf hat z.B. die Fehlermeldung erzeugt:
```
{"topic":"","payload":{"type":"MISSED","id":"0","timestamp":"25.09.23 09:54:59","caller":"","callee":"12345","caller_contacts":[],"callee_contacts":[],"duration":"0"},"_msgid":"fe42873862a97c16"}
``` 
"12345" ist eine meiner Rufnummern. In diesem Fall eine Fax-Nummer.

Folgende Meldungen wurde dabei ausgegeben:
```
The provided number  is not valid for region DE: Error: The string supplied did not seem to be a phone number
``` 
und
```
The provided number 12345 is not valid for region DE
```

**Comment by mapero** [comment]
I will look at it in the next month when updating the nodes and its dependencies.

I can not promise that I find a solution.

**Comment by mapero** [comment]
1.5.0 contains an fallback, if the number can not be normalized a normal string compare will be performed for lookup.
