### ISSUE TITLE
Lookup node changes the call type

### ISSUE THREAD

**Issue by semperor** [bashGroup/node-red-contrib-fritz#13]
The CallMonitor Node gives me 3 msg objects per call. The first has the type "INBOUND", the second the type "CONNECT" and the third the type "DISCONNECT". If I connect the Lookup node directly, the type of the first msg becomes "CONNECT".

**Comment by mapero** [comment]
I can not reproduce this error. Can you post your flow and test with latest version.

**Comment by mapero** [comment]
No response. Closed.
