### ISSUE TITLE
Response: Action failed

### ISSUE THREAD

**Issue by ReneMuetti** [bashGroup/node-red-contrib-fritz#15]
This is my Code:
`[{"id":"9cc08328.f9e3a8","type":"tab","label":"Fritz!Box 6590","disabled":false,"info":""},{"id":"4a594689.e4a93","type":"inject","z":"9cc08328.f9e3a8","name":"MAC: FRITZ!Box 6590","topic":"","payload":"{\"NewMACAddress\":\"CC:XX:XX:XX:XX:XX\"}","payloadType":"json","repeat":"","crontab":"","once":false,"onceDelay":"","x":160,"y":60,"wires":[["a01a7a2c.09fc8","f6c54fa.569a9b"]]},{"id":"a01a7a2c.09fc8","type":"fritzbox-in","z":"9cc08328.f9e3a8","device":"e9520e7a.eb35a8","name":"FRITZ!Box 6590","service":"urn:dslforum-org:service:Hosts:1","action":"GetSpecificHostEntry","arguments":"{\"NewMACAddress\":\"value\"}","x":440,"y":160,"wires":[["8f84c5de.c288a"]]},{"id":"8f84c5de.c288a","type":"debug","z":"9cc08328.f9e3a8","name":"","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"true","x":650,"y":160,"wires":[]},{"id":"f6c54fa.569a9b","type":"debug","z":"9cc08328.f9e3a8","name":"","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"true","x":510,"y":40,"wires":[]},{"id":"e9520e7a.eb35a8","type":"fritzbox-config","z":"","name":"FRITZ!Box 6590","host":"192.168.178.1","port":"49000","ssl":false}]`
Debug-Output:
`16.1.2019, 11:46:59
node: f6c54fa.569a9b
    msg.payload : Object
        object
            NewMACAddress: "CC:XX:XX:XX:XX:XX"`
`16.1.2019, 11:47:00
node: FRITZ!Box 6590
    msg : string[13]
        "Action failed"`

I have created my own account in the Fritzbox for the communication. This account has local admin rights. Only apparently no contact to the FritzBox is possible.
What do I have to change?

**Comment by mapero** [comment]
Did you enable access for applications:
![grafik](https://user-images.githubusercontent.com/1754967/52902842-e0945e80-3216-11e9-971a-63a56031bc3f.png)

**Comment by mapero** [comment]
Please update to the newest version. There you get additional error output.

**Comment by AndyPuettmann** [comment]
You may need to create a dedicated user for your fritz-box to allow all commands to be processed.

If you have the "presence detection" (from: https://flows.nodered.org/node/node-red-contrib-fritz) example working and other queries fail, try to look into issue #16 
I solved it by that dedicated user.

- Andy

**Comment by ReneMuetti** [comment]
Thank you very much.

I have to set up a new NODE-RED first, because the QNAP contained one is too old and an update is not really in sight. Then I will try again.

Many thanks to all helpers for this information.
