### ISSUE TITLE
Action failed - on various actiona

### ISSUE THREAD

**Issue by AndyPuettmann** [bashGroup/node-red-contrib-fritz#16]
Hello there, 
I am running into an issue with my fritz box.

I try to request status info and always get an "action failed" back in node-red.

Example flow:
`[{"id":"311515c.b5a10ea","type":"debug","z":"ad485551.944d98","name":"","active":true,"console":"false","complete":"false","x":730,"y":1000,"wires":[]},{"id":"c630eb69.a44ec8","type":"fritzbox-in","z":"ad485551.944d98","device":"4c92716d.e78db","name":"","service":"urn:dslforum-org:service:DeviceInfo:1","action":"GetInfo","arguments":"{}","x":510,"y":1060,"wires":[["311515c.b5a10ea"]]},{"id":"8afdab17.534268","type":"inject","z":"ad485551.944d98","name":"","topic":"","payload":"{}","payloadType":"json","repeat":"","crontab":"","once":false,"onceDelay":"","x":290,"y":1060,"wires":[["c630eb69.a44ec8"]]},{"id":"4c92716d.e78db","type":"fritzbox-config","z":"","name":"Fritz-Box","host":"fritz.box","port":"49000","ssl":false}]`

Fritzbox:
Model: FRITZ!Box 7490
OS: 07.01

Node-Red-Host:
Raspberry Pi 3b

Tell me if you need any more information.

- Andy

**Comment by mapero** [comment]
Did you enable access for applications:
![grafik](https://user-images.githubusercontent.com/1754967/52902842-e0945e80-3216-11e9-971a-63a56031bc3f.png)

**Comment by AndyPuettmann** [comment]
Yes, I had that enabled.

I got around the problem by adding a complete new fritz-box-user under.
"System - FRITZ!Box-Benutzer"

Interesting fact:
The magazine CT (#5/2019) has an article about Node-Red and the Fritz-Box, they state it may be an error in the firmware of the fritz-box, but properly reading the fields in the configuration node "username" and "password" gave me the hint, that the plain web-interface password may not be enough to work properly. (And it actually fixed the problem, to create a dedicated admin user for NodeRED)

So this issue is solved for me, thank you for your help.
