### ISSUE TITLE
"Action Failed" on some MAC-addresses

### ISSUE THREAD

**Issue by tuffig** [bashGroup/node-red-contrib-fritz#18]
I want to use ist for presence-detection, so I look for MAC-adresses.
Most devices like my PC, raspi and router respond correct, but other like
my iphone not. "Action Failed" ist always the returned message.
Is there some issue with older Fritzboxes?
FB 7270 OS 06.06 / iphone SE

**Comment by mapero** [comment]
Not that I know.
Do you use repeater in your network?

Can you post your flow?

Thanks.

**Comment by tuffig** [comment]
I updated the version in Node-Red to 1.3.1. 
The error changed to "Action failed with error: 500: Internal Server Error".

I use a lancom router as my primary router. 
Router and fritzbox are connected over a LAN-Switch.
Fritzbox show all devices 'online' in the networklist.

iphone se (OS 12.1.4):
   connected to router => Fail
   connected to fritzbox => Fail

Tablet:
   connected to router => Ok
   connected to fritzbox => Ok
 
Huawei P20:
   connected over a second fritzbox (on LAN-Switch) and a FritzRepeater => OK
   Device is queryed over the first Fritzbox

When sending 'xx:xx:xx:xx:xx:xx' as MAC, the same error occurs.
Maybe the iphone MAC address is not considered valid? - I copied it, so no typo-problem.

My Flow with 'xx:xx:xx:xx:xx:xx' as MAC:

[{"id":"5969e3a.6a5b91c","type":"debug","z":"cf329926.1c59f8","name":"","active":true,"tosidebar":true,"console":false,"complete":"false","x":770,"y":400,"wires":[]},{"id":"f87719df.b9f898","type":"fritzbox-in","z":"cf329926.1c59f8","device":"7872eccc.245114","name":"","service":"urn:dslforum-org:service:Hosts:1","action":"GetSpecificHostEntry","arguments":"{\"NewMACAddress\":\"value\"}","x":590,"y":400,"wires":[["5969e3a.6a5b91c"]]},{"id":"f2af4e70.1d1d6","type":"inject","z":"cf329926.1c59f8","name":"iPhone SE","topic":"","payload":"{\"NewMACAddress\":\"xx:xx:xx:xx:xx:xx\"}","payloadType":"json","repeat":"","crontab":"","once":true,"onceDelay":"6","x":370,"y":400,"wires":[["f87719df.b9f898"]]},{"id":"7872eccc.245114","type":"fritzbox-config","z":"","name":"","host":"fritz.box","port":"49000","ssl":false}]

**Comment by mapero** [comment]
500: Internal Server Error normally means that the request can not be handled by the fritzbox, something internal. Did you copy the mac from the network list of the fritzbox?

**Comment by tuffig** [comment]
Yes, I copied it. I also tested it by typing.

**Comment by mapero** [comment]
Do you use MAC randomization on your iphone?

**Comment by tuffig** [comment]
No, native MAC

**Comment by tuffig** [comment]
Update:
I got a new fritzbox-model and it works now. Also via a repeater.
