### ISSUE TITLE
How can i use a different port for the connection.

### ISSUE THREAD

**Issue by wernersv** [bashGroup/node-red-contrib-fritz#2]
Hello,
first of all, this is a great piece to query AVM devices. It is working great on my local node-red installation when i am inside the same network as my fritzbox.

How can I access the fritz box using a different port using a secured connection. eg. SSL port is set to a value different than default SSL port? 

I am trying to access the FB using a secure gateway client (IBM Bluemix). This creates a gateway host with an endpoint/port that gets forwarded to the client inside my network. The port created by the gateway can not be selected/set to the default ports for the FB.

After having a short look at the sources it looks the node is currently using http only (not sure, i'm new to nodejs). 

Sven

**Comment by mapero** [comment]
Hi sven, thanks for your Feedback. Currently the Port is hardcoded to 49000. This should be changed in the upcoming Version. I'll Look into it. Thanks, Jochen
