### ISSUE TITLE
Phonebook - damaged all flows

### ISSUE THREAD

**Issue by Andy4handy** [bashGroup/node-red-contrib-fritz#20]
A flow with Phonebook destroys all existing flows. Some connections disappear in the flows. Only after logging off and logging in again will the error become visible.

**Comment by mapero** [comment]
Thanks for your report.

Can you give me some more information how to reproduce?
Can you post your flow?

**Comment by Andy4handy** [comment]
[Backup_Flow2_2019_02_18.txt](https://github.com/bashGroup/node-red-contrib-fritz/files/2874425/Backup_Flow2_2019_02_18.txt)

I can adjust it by importing the old Flow2. All flows work ok until I log out.

**Comment by mapero** [comment]
Can not reproduce. Closed for now.
