### ISSUE TITLE
Problem accessing DECT-device

### ISSUE THREAD

**Issue by vio2000** [bashGroup/node-red-contrib-fritz#21]
Hi, 
when I try to connect to a smarthome device, I get the following error:
Action failed with error: 401: Unauthorized

My Node
[{"id":"483e2ee9.98bf6","type":"debug","z":"713aab5c.745444","name":"","active":true,"console":"false","complete":"false","x":648,"y":402,"wires":[]},{"id":"9c3e7c5a.3e365","type":"fritzbox-in","z":"713aab5c.745444","device":"ec613813.a596f8","name":"","service":"urn:dslforum-org:service:X_AVM-DE_Storage:1","action":"GetInfo","arguments":"{}","x":428,"y":462,"wires":[["483e2ee9.98bf6"]]},{"id":"ccfb1632.296228","type":"inject","z":"713aab5c.745444","name":"","topic":"","payload":"{}","payloadType":"json","repeat":"","crontab":"","once":false,"onceDelay":"","x":208,"y":462,"wires":[["9c3e7c5a.3e365"]]},{"id":"ec613813.a596f8","type":"fritzbox-config","z":"","name":"Fritzbox","host":"192.168.178.1","port":"49443","ssl":true}]

thanks in advance for your help.
VIO
PS: I try to get temperaturevalues from the dect-smarthome-devices

**Comment by mapero** [comment]
Hi, are the credentials for the Fritzbox correct? Did give the user permission to access smart home devices? Thanks.

**Comment by vio2000** [comment]
Hi, 
I found the solution for my problem.
If you use the Fritzbox services with the X in the name, you need to use a user/password, not only the standards access of the Fritzbox.
Now it works really great. And I can access all the Fritz DECT devices and collect the temperature values.
Thanks for this really good work
Vio
