### ISSUE TITLE
Which function are available?

### ISSUE THREAD

**Issue by mat-l** [bashGroup/node-red-contrib-fritz#22]
Dear @mapero 
Thanks for your work and the implementation of node-red-contrib-fritz which I just downloaded a few days ago. :)
I I am understand correctly, then you are connecting node-red-contrib-fritz to the Fritzbox API? Is there some kind of function / API overview that can be used with node-red-contrib-fritz to realize additional use cases next to "presence detection", "callmonitor"?
Best
matl

**Comment by mapero** [comment]
You can use any function your Fritzbox is providing. It will be dynamically loaded from the device. Checkout https://avm.de/service/schnittstellen/ for a list.

**Comment by vio2000** [comment]
Hi,
can you give me/us an example, how to set the "NewHkrSetTemperature"
Thanks in advance
yours
Markus

**Comment by mapero** [comment]
#23 Duplicate
