### ISSUE TITLE
Lookup - Contact with double zero not found (007207xx)

### ISSUE THREAD

**Issue by Andy4handy** [bashGroup/node-red-contrib-fritz#24]
I search for numbers with 00720710771 (example). But it doesn't work. Any other numbers were found with one zero (089123456). See Flow example.
LG Andy

[Flow_Lookup.txt](https://github.com/bashGroup/node-red-contrib-fritz/files/2899994/Flow_Lookup.txt)
![telefonbuch](https://user-images.githubusercontent.com/42213666/53330483-dfd28b00-38ee-11e9-8891-4fcaab36e412.jpg)
![flow_lookup](https://user-images.githubusercontent.com/42213666/53330739-8cad0800-38ef-11e9-819d-154481cabcd0.jpg)

**Comment by mapero** [comment]
Hi can you tell me more about the double zero number?

I use the phoneutils from google to parse the phone number into a compareable format. My guess is, that it is not a valid number for the selected region.

Thanks.

**Comment by mapero** [comment]
I added some warnings when returning empty array.

**Comment by mapero** [comment]
Okay. I have digged a little into the problem.
I updated the library and checked with a valid number. Its working for me now.
Did you set the country code correctly?

https://github.com/google/libphonenumber/blob/master/FAQ.md#why-wasnt-00-parsed-the-same-as-

**Comment by Andy4handy** [comment]
I do not use specific country codes. I take the 00 number from the Call Monitor and check if it is available in the phone book. 00 means abroad in Germany. In my example, both numbers were present in the telephone book and the buttons simulate an event that comes via the Call Monitor. My provider does not put a specific country code in front of a foreign number. 
With version 1.37 I still can't search with 00 in the telephone book. 
Now I get a hint: "The provided number 00720710771 is not valid for region DE". Ok, 007x stands for Kazakhstan. 
I get the same message for +720710771.

**Comment by Andy4handy** [comment]
Now there are always 6 additional messages for the German number. Example: 0201xx, 0176xx 

"The invalid phonebook number **9 for region DE will be ignored: Error: The string supplied did not seem to be a phone number"
"The invalid phonebook number **1 for region DE will be ignored: Error: The string supplied did not seem to be a phone number"
"The invalid phonebook number +49 for region DE will be ignored: Error: The string supplied did not seem to be a phone number"
"The invalid phonebook number **9 for region DE will be ignored: Error: The string supplied did not seem to be a phone number"
"The invalid phonebook number **1 for region DE will be ignored: Error: The string supplied did not seem to be a phone number"
"The invalid phonebook number +49 for region DE will be ignored: Error: The string supplied did not seem to be a phone number"

**Comment by mapero** [comment]
The numbers with stars as prefix will be ignored in future version and not throwing a warning.

For your number 00720710771: It does not seem to be a valid number. I tested it with the number of the german embassy without problem:
+77172791200
0077172791200

It is working fine for me.

Are you sure your number provided is valid?

**Comment by mapero** [comment]
Warnings are removed for ** numbers with v1.3.9

**Comment by Andy4handy** [comment]
Thanks, the number's actually wrong. I didn't realize until now that there was a plausibility check on the number. Now everything makes sense. The test with 0077172791200 was successful it comes only a warning message. In short, only checked numbers are allowed in the phone book.
