### ISSUE TITLE
Presence detection for users of Guest Wifi

### ISSUE THREAD

**Issue by FordAndii** [bashGroup/node-red-contrib-fritz#25]
Hi,

I tried the presence detection and it works fine with users who use the "standard" Wifi of the FritzBox. However, if I want to implement presence detection for a specific user who is using the Guest Wifi, it only works as long as he is logged into the Wifi. Then the value "NewActive: 1" is submitted by the node.

As soon as the guest user is logged out, the FritzBox forgets about his device and the node submits an error:

![grafik](https://user-images.githubusercontent.com/48220859/53767314-b65cc500-3ed5-11e9-829d-4e0f6970c514.png)

This is the node configuration:

![grafik](https://user-images.githubusercontent.com/48220859/53767455-2b2fff00-3ed6-11e9-8195-841a64d0f1ec.png)

Is there any way to implement presence detection for a specific guest user?

**Comment by mapero** [comment]
Hi FordAndii,

you can use the Hosts GetSpecificHostEntry for this with some limitation.

The Fritzbox is not storing the Macs for Guest Clients. So as soon a client is offline, the fritzbox will forget about the mac. So when guest is online, you will get a response, when offline you will get the error above. My solution is to use a catch node to catch the error and send a false:

`
[{"id":"a5598c9e.5aa55","type":"catch","z":"7d0a8b6e.82f574","name":"","scope":["850c63ba.8503e"],"x":460,"y":260,"wires":[["6f0ee127.5ad33"]]},{"id":"6f0ee127.5ad33","type":"function","z":"7d0a8b6e.82f574","name":"to Boolean","func":"msg.payload = false;\ndelete msg.error\nreturn msg;","outputs":1,"noerr":0,"x":630,"y":260,"wires":[["377edbcb.fc3e24","69fa1ad1.025934"]]},{"id":"850c63ba.8503e","type":"fritzbox-in","z":"7d0a8b6e.82f574","device":"de26e1e7.52398","name":"","service":"urn:dslforum-org:service:Hosts:1","action":"GetSpecificHostEntry","arguments":"{\"NewMACAddress\":\"value\"}","x":430,"y":100,"wires":[["3486ab5c.513b94","69fa1ad1.025934"]]},{"id":"3486ab5c.513b94","type":"function","z":"7d0a8b6e.82f574","name":"to Boolean","func":"msg.payload = msg.payload.NewActive == 1;\nreturn msg;","outputs":1,"noerr":0,"x":610,"y":100,"wires":[["377edbcb.fc3e24"]]},{"id":"de26e1e7.52398","type":"fritzbox-config","z":"","name":"Fritz!Box","host":"192.168.80.1","port":"49000","ssl":false}]
`
