### ISSUE TITLE
"Device not ready" error - related to FritzBox 7.10 update?

### ISSUE THREAD

**Issue by Vermatic** [bashGroup/node-red-contrib-fritz#27]
I have been using node-red-contrib-fritz for a simple presence detection using a Fritz!Box 7580 and FritzOS 7.02 successfully.

Due to unknown reasons my configuration has stopped a few days ago. The Fritzbox node now constantly says "Device not ready".

I did not do any changes to my node-red setup when my configuration stopped working. 
I now checked that the TR-064 interface has not been disabled accidentally in the FritzBox configuration, it is still active.
Also I checked that access via TR-064 via SSL using the FritzBox user I have been using is still working - I am using a small shell script for that. It still works.

However I noticed that the FritzBox received an update to FritzOS 7.10 last week. Is it possible that something has changed here which made node-red-contrib-fritz stop working?

Can anybody please confirm that node-red-contrib-fritz is still working with FritzOS 7.10?

**Comment by Vermatic** [comment]
I can now confirm that my FritzBox running 7.10 is working again.
I disabled both TR-064 and UPNP support and removed the special node-red user I have been using and restarted the FritzBox. Then I enabled both TR-064 and UPNP support again and restarted the FritzBox another time. Then I added back the special node-red user and now it is working again.

**Comment by superwinni2** [comment]
Same error here...
Also did the same... 
- Deleted user and deactivated TR-064 and UPNP
- Restart
- Activated TR-064 and UPNP
- Restart
- Added User again
- Restart
- Test success
