### ISSUE TITLE
1750e repeater, cannot use tr064 because it has no IGD?

### ISSUE THREAD

**Issue by csmale** [bashGroup/node-red-contrib-fritz#29]
I am trying to read the device logs from my 7581 and two 1750e repeaters using Fritz!OS 7.0x in a mesh configuration. Reading the log from the 7581 works fine, but the repeaters give "Device not ready in NodeRed. If I look with Wireshark, things start to diverge at the request for igddesc.xml which succeeds in the 7581 but gives a 404 in the repeaters. Looking at the code, it looks like both IGD and TR064 need to be working to get anywhere. Eg fritz.js line 20: 		Promise.all([fritzbox.initIGDDevice(), fritzbox.initTR064Device()])

Is there some way I can work around this, so I can use the TR064 functions without IGD working? Or have I misunderstood something?

**Comment by mapero** [comment]
@csmale can you test with 1.3.4

**Comment by csmale** [comment]
Sorry, 1.3.4 causes some problem with the config nodes. I switched back to 1.3.3 and this problem goes away again, but the original issue of course still occurs. Any ideas?
![image](https://user-images.githubusercontent.com/1978633/59117859-176dbc00-894f-11e9-98a0-c894097c5787.png)

**Comment by mapero** [comment]
Did some copy paste error on 1.3.4. sorry for that. Please try latest. Tahnks
