### ISSUE TITLE
Output External IP Address

### ISSUE THREAD

**Issue by k1ngf15h3r** [bashGroup/node-red-contrib-fritz#3]
I try to Output the external IP address in the debug but I got soap errors. I also see no arguments which could be provided to a json

**Comment by mapero** [comment]
Hi,

sorry to here that you have problems with the nodes.

But without further information I am not able to help you. What did you configure in the node? What do you send as input?
Can you provide an example flow?

Thanks,
Jochen

**Comment by k1ngf15h3r** [comment]
My fault. I had to use the wanpppconnection.

Am 02.10.2016 12:27 schrieb "mapero" <notifications@github.com>:
