### ISSUE TITLE
Provided number is not valid for region DE

### ISSUE THREAD

**Issue by zampan0** [bashGroup/node-red-contrib-fritz#33]
After upgrading to the latest version (1.3.9) of node-red-contrib-fritz I get always the above message for incoming and outgoing calls. In addition to that, there is the message 
"The invalid phonebook number 500@hd-telefonie.avm.de for region DE will be ignored: Error: The string supplied did not seem to be a phone number"

I have a Fritzbox 7490 with OS 7.01. The previous version(s) of node-red-contrib-fritz worked flawlessly. 
Any ideas what the problem might be ? 
Thank you in advance

**Comment by datag** [comment]
Message shows up in the logs in my installation as well. There is an address book entry (I guess TAM) with this number.

I also get this message for my local/own number on incoming calls, as the number is only stored with its local part.

**Comment by underwoodblog** [comment]
Same here with Fritzbox 7590 and OS 7.12. Node-Red 0.20.7 and node-red-contrib-fritz 1.3.9.

**Comment by MrDrache333** [comment]
Same here

**Comment by ozett** [comment]
maybe related to https://github.com/bashGroup/node-red-contrib-fritz/issues/41  ?

**Comment by ozett** [comment]
any progress here? message still persists...

**Comment by ozett** [comment]
easy solution: delete this entry in your phonebook.
after deletion, the message is gone.

![image](https://user-images.githubusercontent.com/5937811/71808808-00bb4f00-306f-11ea-92bc-2a1546d2366d.png)


 500@hd-telefonie.avm.de is a testing-number for HD-Quality, i guess.
maybe it helps to disable hd-quality in fritzbox.

or the sourecode must still be updated to consider sip-numbers also as valid phonebook entries.

**Comment by mapero** [comment]
sip uris are currently not supported. I have updated the code so it skips sip uris while iterating the phonebook. That will remove the warning.

If you require the lookup node also work with sip uris create a feature request.

Thanks.
