### ISSUE TITLE
Unable to Add a portmapping

### ISSUE THREAD

**Issue by emme73** [bashGroup/node-red-contrib-fritz#34]
On a Fritz 7490 I'm unable to add PortMapping for service WanIPConfiguration

the JSON I'm sending is:
{
    "NewRemoteHost": "0.0.0.0",
    "NewExternalPort": "3674",
    "NewProtocol": "TCP",
    "NewInternalPort": "3674",
    "NewInternalClient": "192.168.0.5",
    "NewEnabled": "1",
    "NewPortMappingDescription": "Device",
    "NewLeaseDuration": "0"
}

The reply is Server Error 500

I think this is a modem issue, but I'm wondering f the paylos is compiled correctly.......

There are other options that are not available (still with error 500) but I'm able to read exisitng portmapping, but not able to add new....

**Comment by mapero** [comment]
From the tr064 documentation:
![image](https://user-images.githubusercontent.com/1754967/94729804-894aef80-0362-11eb-9cf5-402adf20135d.png)

Is node-red running on the 192.168.0.5?

**Comment by mapero** [comment]
Closed. If that was not the reason, pleade reopen.
