### ISSUE TITLE
"Something went wrong" on enumerating services

### ISSUE THREAD

**Issue by kaennchenstruggle** [bashGroup/node-red-contrib-fritz#35]
I have other devices properly accessing my Fritz!Box using TR-064 but with this node I'm a little puzzled.

I always get "something went wrong" message  when trying to enumerate services.

The following I attempted
-> create user and enter name + password
-> use "no user" + single password
-> use "dslf-config" + single password
-> change port to 49443 (+ enable SSL)
-> change from IP address to hostname

But all without success.

Can you please help?

**Comment by mapero** [comment]
@kaennchenstruggle I need more input if this issue is still relevant. Can you provide an example flow?

**Comment by mapero** [comment]
Closed. Please reopen if necessary.
