### ISSUE TITLE
Presence detection - Device appears always as connected to WLAN

### ISSUE THREAD

**Issue by djiwondee** [bashGroup/node-red-contrib-fritz#39]
Hello,

I'm using node-red-contrib-fritz for a very long time and I'm happy with the functionality

- Call list
- Enabling Guest WLAN´
- Presence detection by injecting a MAC address of my mobile phone

Since a couple of weeks those injected phone MAC are always present even if it is in flight mode or really far away from home. So my guess is FRITZ OS 7 I'm using doesn't really respond the real status. This is how my flow looks like:

<img width="1187" alt="image" src="https://user-images.githubusercontent.com/37173958/67082288-2126ec00-f199-11e9-993d-e94dbebc5127.png">

I'm using the value `NewActive` value from the payload which is always `1`:

`{"NewIPAddress":"192.168.178.22","NewAddressSource":"DHCP","NewLeaseTimeRemaining":"0","NewInterfaceType":"802.11","NewActive":"1","NewHostName":"****"}`

Based on my investigation so far I guess there is a problem within FritzOS here. I also see the mobile connected to WLAN in the console for FritzOS.

--> Are you aware of that? 
--> Is there a different API I could call to get the real status?

**Comment by djiwondee** [comment]
After playing around with that I'm getting the glue for the reason. I'm running a Mesh WLAN and it seems only for devices not directly connected to the fritz:box but with the mesh repeaters showing this behaviors. Have also opened a support track at AVM.

**Comment by LeopoldKing** [comment]
Have you received any reply on that issue from AVM?

**Comment by djiwondee** [comment]
@LeopoldKing Yes I’m still in conversations with AVM. Will have some news in the next couple of days.

**Comment by LeopoldKing** [comment]
Great. I found out that it seems to update the status of my devices after a while but it’s not reacting as fast as it was before.

**Comment by djiwondee** [comment]
Hello @LeopoldKing,

the response from AVM was very precisely and it seems to solve the problem. Mainly one of the following action will solve the problem

1. Make sure you have the most recent firmware installed -  in my case I'm running a 7590 and two different fritz repeater in mesh operation mode and one repeater was not on `7.12`
2. Reduce the DHCP lease time from 10 to one day
3. Disconnect all clients but one LAN connected for accessing the FRITZ OS console in a browser
4. Remove all clients from the list of known unused connections
5. Unplug any repeater and finally the Fritz!Box from power supply
6. Wait at least 10 minutes
7. Take FritzBox and repeater back into operation step by step

I played around after following that instructions  by forcing WLAN-connection of my devices to repeater (acting as mesh client and Fritz!Box (acting as the mesh-master). Since a couple of days the [flow above](https://github.com/bashGroup/node-red-contrib-fritz/issues/39#issue-508962852) works as expected and how the flow did it after the initial setup. AVM stated:

> The firmware update is only the first step here, the "DHCP-legacy" have to be removed as well.
