### ISSUE TITLE
How to get NewTotalBytesReceived/NewTotalBytesSent of the current month

### ISSUE THREAD

**Issue by codmpm** [bashGroup/node-red-contrib-fritz#4]
Hi guys,

sorry to bother you again....

Do you know if I can find the total data-volume "wasted" for the current month (!), like it is shown in the online counter of the fritz.box?
The two values from the title only give me the total bytes since the last restart of the box. Would be interesting, due to netflix etc., to know how many gigabytes were transfered the current month.

Cheers,
Patrik

**Comment by mapero** [comment]
This is not possible since avm does not provide an api to fetch this data. I would recomend to use node-red to push the values to a database (e.g. influxdb) every day or hour and then use node-red again to create a diff between two values.

**Comment by codmpm** [comment]
Thank you for the clarification 👍
