### ISSUE TITLE
401-error to phonebook on latest fritzos7.12

### ISSUE THREAD

**Issue by ozett** [bashGroup/node-red-contrib-fritz#40]
![image](https://user-images.githubusercontent.com/5937811/68204458-566c7000-ffc8-11e9-97cc-83e849468e49.png)

my credentials to access the box work ok (actually: no name, but password in the local-lan) and i have debug-infos about access the box and the events,
but the phonebook lookup is not working (yes, i did the #96 * 5 *).

as i found no more information about that, i have to ask here for a solution.
do i need user with name+password activated for local-access to phonebook?
can i more verbosely debug the 401-error?

![image](https://user-images.githubusercontent.com/5937811/68204847-27a2c980-ffc9-11e9-83c4-a3b059f910bc.png)

**Comment by ozett** [comment]
any progress on this? anybody out there to help/update?
or is it misconfiguration?

**Comment by ozett** [comment]
i created a new user and provided this new credentials in a additional config to the phonebook-lookup-node. that worked.

dont know why the other fritz-nodes worked with my other user and pwd....

maybe OS 7.x related?

**Comment by gsieben** [comment]
> i created a new user and provided this new credentials in a additional config to the phonebook-lookup-node. that worked.

I tried the same thing. After I created a second user in the Fritz.Box and let the lookup search over it, everything worked. After that, I deleted the user and used the same user that led to 401 before. This time without problems. This is a definite bug.

**Comment by mapero** [comment]
> > i created a new user and provided this new credentials in a additional config to the phonebook-lookup-node. that worked.
> 
> I tried the same thing. After I created a second user in the Fritz.Box and let the lookup search over it, everything worked. After that, I deleted the user and used the same user that led to 401 before. This time without problems. This is a definite bug.

@gsieben Sounds more like a bug on FritzOS than on the node side, since the 401 comes from the box. I can hardly reproduce this, because I only own one fritzbox with multiple users which is used in production. 

@ozett I am also not sure that an empty username is valid, maybe fritzbox expects something like admin or root. Can you try this?

**Comment by ozett** [comment]
@mapero 
empty username on fritzbox is valid. you can ommit all security in your own network .
(see notice on screenshot of fritzbox-os in my first post here.

as gsieben stated, there seems to be a bug with loggin in while only one uses exits on the box. 
maybe that has to be investigated?

**Comment by mapero** [comment]
I can confirm that an empty username is not allowed using tr064. I set my fritzbox to password only:
![image](https://user-images.githubusercontent.com/1754967/94722833-25232e00-0358-11eb-8996-7481c98c2848.png)

using blank username in nodes results in 401, using a random username "thisuserdoesnotexists" works for me. This also matches the tr064 documentation:
https://avm.de/fileadmin/user_upload/Global/Service/Schnittstellen/AVM_Technical_Note_-_Konfiguration_ueber_TR-064.pdf

> Anmeldung mit dem FRITZ!Box-Kennwort
> Nutzen Sie das FRITZ!Box-Kennwort, das Sie auch zur Anmeldung an die Benutzeroberfläche verwenden.
> Der Benutzername kann frei gewählt werden.

Can you please confirm that non-empty username works for you. Do not use an existing user for the test.

Thanks.

**Comment by ozett** [comment]
i kept the old users password, but used a "non-existing" username.
that worked. 
( i assume it should not, but if tr064 allows "no auth" than this is the explanation why it worked)

![image](https://user-images.githubusercontent.com/5937811/94830297-ba332f00-040b-11eb-9248-e887c014429c.png)
