### ISSUE TITLE
Dect!200  Internal Server Error

### ISSUE THREAD

**Issue by Frogy76** [bashGroup/node-red-contrib-fritz#42]
It is possible to turn the plug on but it gets this error when it was turned off

"Action failed with error: 500: Internal Server Error"

**Comment by mapero** [comment]
Can you provide an example flow to reproduce the issue.

I do not own the plug but will try to look into this.

**Comment by P1Rebo** [comment]
Everything worked fine using version 1.4.2.

Code I used see here:

`[{"id":"f312b5e7.3a4ed8","type":"fritzbox-in","z":"770548ba.9d76b8","device":"f0f6841f.fb04c8","name":"","service":"urn:dslforum-org:service:X_AVM-DE_Homeauto:1","action":"SetSwitch","arguments":"{\n  \"NewAIN\": \"value\",\n  \"NewSwitchState\": \"value\"\n}","x":470,"y":200,"wires":[["579244de.db3e0c"]]},{"id":"1beba950.31c567","type":"inject","z":"770548ba.9d76b8","name":"","props":[{"p":"payload"},{"p":"topic","vt":"str"}],"repeat":"","crontab":"","once":false,"onceDelay":0.1,"topic":"","payload":"","payloadType":"date","x":180,"y":200,"wires":[["a0c5b576.5dec38"]]},{"id":"a0c5b576.5dec38","type":"function","z":"770548ba.9d76b8","name":"","func":"msg.payload = {\n  \"NewAIN\": \"08761 0229189\",\n  \"NewSwitchState\": \"OFF\"\n};\nreturn msg;\n\n//{\"NewAIN\":\"08761 0229189\", \"NewSwitchState\" : \"ON\"}","outputs":1,"noerr":0,"initialize":"","finalize":"","x":320,"y":200,"wires":[["f312b5e7.3a4ed8"]]},{"id":"579244de.db3e0c","type":"debug","z":"770548ba.9d76b8","name":"","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"true","targetType":"full","statusVal":"","statusType":"auto","x":610,"y":200,"wires":[]},{"id":"f0f6841f.fb04c8","type":"fritzbox-config","z":"","name":"Fritz","host":"192.168.52.1","port":"49000","ssl":false,"user":"admin"}]`
