### ISSUE TITLE
No Service Selection

### ISSUE THREAD

**Issue by martiko70** [bashGroup/node-red-contrib-fritz#45]
Hi,
I am already using some Flows with contrb-fritz and they work fine, also the copied examples do work.

But when I add a new Frritz!Box node to my Flow (and select the already configured Configuratio-Node, which works fine for the existing Flows), the drop down List for the Service Selection remains empty (there is just a grey line in the drop down list)

Any Idea how to solve this issue?

**Comment by e-lange** [comment]
Hello all,

I can fully reproduce this issue. Is there anything to support solving this issue?
Does anybody happen to have a work-arouond for this?

Somehow this renders the node unusable...

Thanks

**Comment by solick** [comment]
Hi i can confirm this bug. Is this project still under maintenance?

**Comment by mapero** [comment]
Duplicate of #43
