### ISSUE TITLE
Always getting "Sorry. Your selected device is invalid!"

### ISSUE THREAD

**Issue by JsBergbau** [bashGroup/node-red-contrib-fritz#46]
I've configured the "Fritz!Box" Node

![grafik](https://user-images.githubusercontent.com/37013344/83430385-20d81a00-a425-11ea-8a21-18bc0ae1e4ab.png)

When opening I get

![grafik](https://user-images.githubusercontent.com/37013344/83430337-043be200-a425-11ea-926d-a253f92c2c4a.png)

It gets even stranger. 

If you add node-red-contrib-tplink https://flows.nodered.org/node/node-red-contrib-tplink
![grafik](https://user-images.githubusercontent.com/37013344/83430466-4107d900-a425-11ea-98d5-64ba3f55b6ee.png)

You  just need to add it. There is no need to add the node to the flow, not to mention to configure it. So you can try even if you don't have any tplink smartplug.

You get in node-red-log a very strange error

```

1 Jun 17:22:17 - [error] [fritzbox-in:83101963.6ccf28] TypeError: Cannot read property 'on' of null
1 Jun 17:22:17 - [info] Gestartete geänderte Nodes
TCP 553052de.75daec:9999 Error: getaddrinfo ENOTFOUND 553052de.75daec
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:66:26) {
  errno: 'ENOTFOUND',
  code: 'ENOTFOUND',
  syscall: 'getaddrinfo',
  hostname: '553052de.75daec'
}
(node:17480) UnhandledPromiseRejectionWarning: Error [ERR_HTTP_HEADERS_SENT]: Cannot set headers after they are sent to the client
    at ServerResponse.setHeader (_http_outgoing.js:518:11)
    at ServerResponse.header (/usr/lib/node_modules/node-red/node_modules/express/lib/response.js:771:10)
    at ServerResponse.send (/usr/lib/node_modules/node-red/node_modules/express/lib/response.js:170:12)
    at /home/pi/.node-red/node_modules/node-red-contrib-tplink/nodes/smart-plug.js:305:50
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
(node:17480) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:17480) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```
Whats happening here? I've worked with the TP-Link Node for a while, but this error started when I used the FritzBox Node

![grafik](https://user-images.githubusercontent.com/37013344/83430688-9e038f00-a425-11ea-84c6-df12d298f6e0.png)

PS: The node works, you can query the Box, despite the error message. But there seems to go something really wrong....

Why does using this node affect tp-link node? Can't see how they should be linked.

Hope you can find out whats going on here, because I'm afraid this error can destroy working flows.

**Comment by P1Rebo** [comment]
@JsBergbau,
I just tried to reproduce your error here and couldn't. Using node-red-contrib-tplink v1.0.0 everything seems to work.
Please doublecheck that and give us any feedback, if you still have this issue.

**Comment by JsBergbau** [comment]
They've changed a lot with new TP-Link Plugin. A lot of things didn't work anymore, you had to rewrite a lot of flows, because of the old version beeing not compatible anymore with the old version. That are things that shouldn't happen. I still use the old version of TP-Link, 0.2.1 as seen in the screenshot above. And in the meantime a new node red version was released. At least for me it works now.
