### ISSUE TITLE
Service "dslforum-org" Internal Server Error

### ISSUE THREAD

**Issue by lingelf** [bashGroup/node-red-contrib-fritz#47]
Hi guys,

getting an error for all services with:
"urn:dsforum-org*" -->
**"Action failed with error: 500: Internal Server Error"**

Services for "urn:schemas-upnp-org*" are working fine.

FB7390 FRITZ!OS: 06.86

Any hints? Know Issue?

Thank you.

**Comment by mapero** [comment]
@lingelf Can you provide an example flow so I can reproduce it? Thanks.

**Comment by mapero** [comment]
Closed. Please reopen if necessary.

**Comment by lingelf** [comment]
@mapero sorry for the late response. This is an example flow where the error actually occurs. As described it is working for the "urn:schemas-upnp-org*" Services.

[{"id":"9fbabfd1.529a5","type":"debug","z":"7476bb3b.227304","name":"","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"payload","targetType":"msg","x":870,"y":740,"wires":[]},{"id":"b21fb225.06e5a","type":"fritzbox-in","z":"7476bb3b.227304","device":"e7861b21.4aa148","name":"","service":"urn:dslforum-org:service:LANHostConfigManagement:1","action":"GetDNSServers","arguments":"{}","x":540,"y":740,"wires":[["9fbabfd1.529a5"]]},{"id":"72631b53.5d3ca4","type":"inject","z":"7476bb3b.227304","name":"","topic":"emtyJSON","payload":"{}","payloadType":"json","repeat":"600","crontab":"","once":true,"onceDelay":"0.9","x":280,"y":740,"wires":[["b21fb225.06e5a"]]},{"id":"e7861b21.4aa148","type":"fritzbox-config","z":"","name":"FritzBox","host":"fritz.box","port":"49443","ssl":true}]

"Action failed with error: 500: Internal Server Error"

Do you need further details for debugging?
