### ISSUE TITLE
Tried the precence example but i get an error: "TypeError: Cannot read property 'actions' of undefined"

### ISSUE THREAD

**Issue by DeepHyperspace** [bashGroup/node-red-contrib-fritz#50]
No matter what i try, i always get this error, is this node still working? FritzBox 6490 Cable with 7.12 FritzOS
"TypeError: Cannot read property 'actions' of undefined"

**Comment by Nerdiyde** [comment]
Hey,
I had the same issue and found out how to solve it. I wrote an article about that on my blog. You can finde it here:
German version: https://nerdiy.de/howto-fritzbox-fehler-typeerror-cannot-read-property-actions-of-undefined-in-der-node-red-contrib-fritz-node-beheben/
English version: https://nerdiy.de/en/howto-fritzbox-fehler-typeerror-cannot-read-property-actions-of-undefined-in-der-node-red-contrib-fritz-node-beheben/

If you like let me know if it helped. :)

**Comment by DeepHyperspace** [comment]
> Hey,
> I had the same issue and found out how to solve it. I wrote an article about that on my blog. You can finde it here:
> German version: https://nerdiy.de/howto-fritzbox-fehler-typeerror-cannot-read-property-actions-of-undefined-in-der-node-red-contrib-fritz-node-beheben/
> English version: https://nerdiy.de/en/howto-fritzbox-fehler-typeerror-cannot-read-property-actions-of-undefined-in-der-node-red-contrib-fritz-node-beheben/
> 
> If you like let me know if it helped. :)

Hi thanks for your reply. Sounds like you found the solution, i will try it as soon as i can.
