### ISSUE TITLE
get information on telephony if it is offline

### ISSUE THREAD

**Issue by averlon** [bashGroup/node-red-contrib-fritz#54]
Hi,
I have searched around for information but did not find what I need so I go the way to ask here for help.

Is there a way to find out whether phone numbers configured in the FRITZ!Box are not registered. Means, telephony via this phone number is not possible.
There can be various reasons for a phone number beeing offline. No Internet, no SIP ....

But I would like to be informed once this happens.

Which service do I need to check via node-red-contrib-fritz to find out?

Thanks
Kallewirsch

**Comment by P1Rebo** [comment]
Hi, did you check out the TR-064 documentation already? I guess.

**Comment by averlon** [comment]
Hi, no - where to find ?

**Comment by P1Rebo** [comment]
Here we go: 
I don't know if there is any in EN.
https://avm.de/service/schnittstellen/ => Apps / TR-064

**Comment by averlon** [comment]
Hi,
thanks for your reply, but it does not help at all.
I am not able to find aout what service provides what information. It is more a try-and-error run.
Thanks anyway.

**Comment by P1Rebo** [comment]
It's as always with this API :-)
I just player around a little bit. As I see you can get all infos regarding the configured VoIP numbers and also Clients (phone). But I couldn't find any status (online / offline).

`[{"id":"f755e905.8f6928","type":"inject","z":"f619750b.75d568","name":"","topic":"","payload":"","payloadType":"date","repeat":"","crontab":"","once":false,"onceDelay":0.1,"x":260,"y":2160,"wires":[["529cccb7.599a34"]]},{"id":"529cccb7.599a34","type":"fritzbox-in","z":"f619750b.75d568","device":"c64ffd42.a948e","name":"","service":"urn:dslforum-org:service:X_VoIP:1","action":"GetExistingVoIPNumbers","arguments":"{}","x":410,"y":2160,"wires":[["91cdce9c.aef98"]]},{"id":"91cdce9c.aef98","type":"debug","z":"f619750b.75d568","name":"","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"true","targetType":"full","x":550,"y":2160,"wires":[]},{"id":"242c7ea8.abf2b2","type":"inject","z":"f619750b.75d568","name":"","topic":"","payload":"{\"NewVoIPAccountIndex\":\"1\"}","payloadType":"json","repeat":"","crontab":"","once":false,"onceDelay":0.1,"x":250,"y":2200,"wires":[["1ff2c3e8.f9783c"]]},{"id":"1ff2c3e8.f9783c","type":"fritzbox-in","z":"f619750b.75d568","device":"c64ffd42.a948e","name":"","service":"urn:dslforum-org:service:X_VoIP:1","action":"X_AVM-DE_GetVoIPAccount","arguments":"{\"NewVoIPAccountIndex\":\"value\"}","x":410,"y":2200,"wires":[["b531ab1e.28e5c8"]]},{"id":"b531ab1e.28e5c8","type":"debug","z":"f619750b.75d568","name":"","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"true","targetType":"full","x":550,"y":2200,"wires":[]},{"id":"b6d914bf.54db08","type":"inject","z":"f619750b.75d568","name":"","topic":"","payload":"{\"NewX_AVM-DE_ClientIndex\":\"1\"}","payloadType":"json","repeat":"","crontab":"","once":false,"onceDelay":0.1,"x":250,"y":2240,"wires":[["a1ed7070.070f6"]]},{"id":"a1ed7070.070f6","type":"fritzbox-in","z":"f619750b.75d568","device":"c64ffd42.a948e","name":"","service":"urn:dslforum-org:service:X_VoIP:1","action":"X_AVM-DE_GetClient","arguments":"{\"NewX_AVM-DE_ClientIndex\":\"value\"}","x":410,"y":2240,"wires":[["c1673dac.e53e5"]]},{"id":"c1673dac.e53e5","type":"debug","z":"f619750b.75d568","name":"","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"true","targetType":"full","x":550,"y":2240,"wires":[]},{"id":"c64ffd42.a948e","type":"fritzbox-config","z":"","name":"Fritz 1 Test","host":"fritz.box","port":"49000","ssl":false}]`

**Comment by P1Rebo** [comment]
Issue closed. API-related.
