### ISSUE TITLE
Calllist Max results and Max days not working correctly

### ISSUE THREAD

**Issue by cubecell** [bashGroup/node-red-contrib-fritz#55]
Hi,
it seems the query parameters max results and max days are completely ignored.

I think there is a bug in calllist.js (line 54)

`return httpclient.get(url, queryParams)`

In my opinion, maybe it should look like this:

`return httpclient.get(url, { params: queryParams })`

Thanks !

**Comment by mapero** [comment]
You are right. Will fix it later today.
