### ISSUE TITLE
outgoin call creates an error 

### ISSUE THREAD

**Issue by MStri** [bashGroup/node-red-contrib-fritz#56]
Hello, 
I try to make an outgoing call with an injektion 

{    "NewX_AVM-DE_PhoneNumber": "**611" }

and i got error 

"Action failed with error: 500: Internal Server Error"

other things like callmonitor and presence works fine ...

the catch all gives this
error.message
{"message":"Action failed with error: 500: Internal Server Error","source":{"id":"6a576a93.44c0a4","type":"fritzbox-in","count":1}}
error.source
{"id":"6a576a93.44c0a4","type":"fritzbox-in","count":1}

what i would like to do is to place a call 

can i get an idea whats wrong ? 

thanks 

br marcus

**Comment by P1Rebo** [comment]
Hi Marcus, what service are you calling? can you post your code / flow? As I can remember the Fritz API doensn't allow to create a call. Did you verify the documentation? 
https://avm.de/service/schnittstellen/

Regards, Pedro

**Comment by P1Rebo** [comment]
Issue will be closed in +5 days.

**Comment by mapero** [comment]
Hi,

you have to enable this feature first, e.g. over UI:
![image](https://user-images.githubusercontent.com/1754967/103300364-038d1d80-49ff-11eb-8568-04ac65c13627.png)

After that you can call numbers that are in your phonebook. They have to be exactly the number, e.g. +49... and 0... does matter
