### ISSUE TITLE
Is there a way to trigger a reboot of the fritzbox?

### ISSUE THREAD

**Issue by stuckis6er** [bashGroup/node-red-contrib-fritz#57]
Thank you, Ralf.

**Comment by P1Rebo** [comment]
Hi Ralf,  you could check out the DeviceConfig service ([link](https://avm.de/fileadmin/user_upload/Global/Service/Schnittstellen/AVM_TR-064_first_steps.pdf))
Please close this issue if this works.
Regards, Pedro

**Comment by P1Rebo** [comment]
Issue will be closed after +5d.

**Comment by stuckis6er** [comment]
thanks, that was the solution. 

best regards, ralf.
