### ISSUE TITLE
Not installing fritzbox-contact

### ISSUE THREAD

**Issue by Speeedy0815** [bashGroup/node-red-contrib-fritz#58]
Hi,
It’s not possible to install the node-red-controb-fritz at all. And so it’s not working.
fritzbox-contact is missing after installation. Nothing is working exept of the call-monitor.
In Node-Red in window installed-nodes there is showen „AssertionError: Assertion failed (line:4)“.
Your Example to detect Presence shows:
„"Action failed with error: 500: Internal Server Error"“

I think something went wrong during installation.

I tryed also to install via comandshell  same issue.
How can I collect Information for you? I hope you can help me.

Thank you, regards
Speedy

**Comment by Speeedy0815** [comment]
I tested with 2 fritzboxes    --> failing
I tested with 2 Raspberrys  --> failing (Node Red 1.2.5 and 1.0.2)
I tested on an X86 Ubuntu --> is working

So it depends somehow with my Raspberry's.  --> Maybe someone has an Idea to find the right information.

**Comment by Speeedy0815** [comment]
I reinstalled Node-Red completely with deleting all of the installed nodes. It's working now. I don't know the reason, but Issue can be closed.

**Comment by Speeedy0815** [comment]
Now I see the difference. Last comment: It was installed node-red-contrib V1.4.3

I updated to 1.4.4, Now there are the same issues on all test-PC's. So Problem is only on 1.4.4. --> Reopen

**Comment by Speedy0815** [comment]
Please can Someone help? Or maybe someone can help how to detect the reason?

Does someone has an workarround?
