### ISSUE TITLE
No Services response received.

### ISSUE THREAD

**Issue by lingelf** [bashGroup/node-red-contrib-fritz#59]
Getting following error for ALL nodes after update to  Version 1.4.3

"No Services response received."

Example Flow which was working on older version:
[{"id":"2c62cb1b.3fa004","type":"fritzbox-in","z":"7476bb3b.227304","device":"e7861b21.4aa148","name":"Gerät angemeldet?","service":"urn:dslforum-org:service:Hosts:1","action":"GetSpecificHostEntry","arguments":"{\"NewMACAddress\":\"value\"}","x":570,"y":300,"wires":[["6d411e9c.2c189"]]},{"id":"2fdc008f.b8dff","type":"inject","z":"7476bb3b.227304","name":"iPad","topic":"","payload":"{\"NewMACAddress\":\"5C:97:F3:B7:93:AD\"}","payloadType":"json","repeat":"60","crontab":"","once":true,"onceDelay":"5","x":330,"y":300,"wires":[["2c62cb1b.3fa004"]]},{"id":"6d411e9c.2c189","type":"change","z":"7476bb3b.227304","name":"Filter Wifi State","rules":[{"t":"move","p":"payload.NewActive","pt":"msg","to":"payload","tot":"msg"}],"action":"","property":"","from":"","to":"","reg":false,"x":840,"y":300,"wires":[["172824f9.189dfb"]]},{"id":"172824f9.189dfb","type":"ui_switch","z":"7476bb3b.227304","name":"","label":"iPad","tooltip":"","group":"28532e7a.be2ed2","order":6,"width":0,"height":0,"passthru":true,"decouple":"false","topic":"","style":"","onvalue":"1","onvalueType":"str","onicon":"fa-wifi","oncolor":"lime","offvalue":"0","offvalueType":"str","officon":"fa-wifi","offcolor":"grey","x":1050,"y":300,"wires":[[]]},{"id":"e7861b21.4aa148","type":"fritzbox-config","z":"","name":"FritzBox Eichenstraße","host":"fritz.box","port":"49443","ssl":true},{"id":"28532e7a.be2ed2","type":"ui_group","z":"","name":"WiFi","tab":"2acf3df0.c1d3b2","order":3,"disp":true,"width":"6","collapse":false},{"id":"2acf3df0.c1d3b2","type":"ui_tab","z":"","name":"Home","icon":"dashboard","order":1,"disabled":false,"hidden":false}]

The search box is not getting any results from my fritzbox. It is just empty, so iam not able to select a Service.
![image](https://user-images.githubusercontent.com/62721861/100341094-68a6bb00-2fdc-11eb-870e-3e0e050c0a42.png)
Popu up box says: "Services received." but this seems not the case.

Anything I can do here?

FritzBox7390
Version 06.86

Thank you.

**Comment by lingelf** [comment]
no worry dns issue caused this problem....

**Comment by steuerzentrale** [comment]
I have the same problem while trying to configure presence-detection via MAC-address. what exactly was the issue with DNS? maybe I have the same issue.

**Comment by lingelf** [comment]
> I have the same problem while trying to configure presence-detection via MAC-address. what exactly was the issue with DNS? maybe I have the same issue. I use a Fritzbox 4040 on OS 07.14

hard to say if you have the same problem. Try to ping a internetserver from the system you are running nodered. if it is a container connect into the container and execute it within there

**Comment by steuerzentrale** [comment]
thanks for the swift relpy, actually I found the issue. I had to allow the access for applications to read/edit the fritzbox settings. the setting is located under: home network / network / network settings / home network access.

<img width="902" alt="fritzbox" src="https://user-images.githubusercontent.com/75168550/101692128-033cda80-3a70-11eb-982e-64024036e793.png">
