### ISSUE TITLE
Service "dslforum-org" Internal Server Error

### ISSUE THREAD

**Issue by lingelf** [bashGroup/node-red-contrib-fritz#60]
@mapero sorry for the late response. This is an example flow where the error actually occurs. As described it is working for the "urn:schemas-upnp-org*" Services.

[{"id":"9fbabfd1.529a5","type":"debug","z":"7476bb3b.227304","name":"","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"payload","targetType":"msg","x":870,"y":740,"wires":[]},{"id":"b21fb225.06e5a","type":"fritzbox-in","z":"7476bb3b.227304","device":"e7861b21.4aa148","name":"","service":"urn:dslforum-org:service:LANHostConfigManagement:1","action":"GetDNSServers","arguments":"{}","x":540,"y":740,"wires":[["9fbabfd1.529a5"]]},{"id":"72631b53.5d3ca4","type":"inject","z":"7476bb3b.227304","name":"","topic":"emtyJSON","payload":"{}","payloadType":"json","repeat":"600","crontab":"","once":true,"onceDelay":"0.9","x":280,"y":740,"wires":[["b21fb225.06e5a"]]},{"id":"e7861b21.4aa148","type":"fritzbox-config","z":"","name":"FritzBox","host":"fritz.box","port":"49443","ssl":true}]

"Action failed with error: 500: Internal Server Error"

Do you need further details for debugging?

_Originally posted by @lingelf in https://github.com/bashGroup/node-red-contrib-fritz/issues/47#issuecomment-734203460_

**Comment by muckisg** [comment]
Hi, 
i get the same error working on the example from [heise.de](https://www.heise.de/ratgeber/Fritzboxen-mit-Node-Red-auslesen-und-steuern-4307624.html?seite=all) on user presence regognition via MAC adress. 

`[{"id":"b6df9859.aa75c8","type":"tab","label":"Gerät angemeldet?","disabled":false,"info":"Präsenzcheck"},{"id":"1bde0feb.922be","type":"fritzbox-config","name":"FritzBox","host":"***","port":"49443","ssl":true,"user":"***"},{"id":"77e834b1.8dda2c","type":"fritzbox-in","z":"b6df9859.aa75c8","device":"1bde0feb.922be","name":"Maurice@Home","service":"urn:dslforum-org:service:Hosts:1","action":"GetSpecificHostEntry","arguments":"{\n  \"NewMACAddress\": \"value\"\n}","x":460,"y":420,"wires":[["3af2dfb6.06d33"]]},{"id":"8e2b1524.20caa8","type":"inject","z":"b6df9859.aa75c8","name":"Maurice Mobile","props":[{"p":"payload"}],"repeat":"60","crontab":"","once":true,"onceDelay":"5","topic":"","payload":"{\"NewMACAddress\":\"**:24:**:4c:**:**\"}","payloadType":"json","x":230,"y":420,"wires":[["77e834b1.8dda2c"]]},{"id":"3af2dfb6.06d33","type":"debug","z":"b6df9859.aa75c8","name":"","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"payload","targetType":"msg","statusVal":"","statusType":"auto","x":690,"y":420,"wires":[]}]
`

Fritzbox wirh TR-069 api works with python and same credentials, so this is not the fault.

Any ideas?
Kind regards, 
Maurice

**Comment by lingelf** [comment]
i am getting the error error for all services with:
"urn:dsforum-org*" -->
"Action failed with error: 500: Internal Server Error"

Services for "urn:schemas-upnp-org*" are working fine.

**Comment by mapero** [comment]
Hi,

I copied your flow and changed credentials and mac address, working fine for me.

Is the mac known to fritzbox? Can you try with another mac address?

Thanks.

**Comment by mapero** [comment]
Hint: If the device is using the guest wifi, it will be deleted after disconnect and this will result in Error 500 by the fritzbox

**Comment by lingelf** [comment]
> Hi,
> 
> I copied your flow and changed credentials and mac address - working fine for me.
> 
> Is the mac known to fritzbox? Can you try with another mac address?
> 
> Thanks.

Did you try with my flow as well? Is there maybe an issue with the model or version of the fritbox?

**Comment by rollischulze67** [comment]
Hello,

I have the same issue with a FB 6340 Cable.
Help would be great.

Thanks

**Comment by muckisg** [comment]
Hi mapero,

thanx for response. Do i have to whitelist the mac adress? I have no mac adress blocking activated.

Thx,

Maurice

**Comment by muckisg** [comment]
Hi again,

OK, works for me by now. My Pixel 5 device shows a different WLAN MAC ADRESS than my router. in my first tries i copied the mac from my device, now i tested it with the mac adress seen by my router and it works. My Pixel 5 device seems to change the mac within different wifi aps. So that's the problem.

Thx 4 help,

Maurice

**Comment by rollischulze67** [comment]
Hello again,

which modell of the Fritzbox do you use?

If I count the "available" devices with GetHostNumberOfEntries, I always get 16 items for whitch I can get the device via GetSpecificHostEntry.
For all the other additional devices (about 90), I get the "Action failed with error: 500: Internal Server Error" when I try to get them via "NewMACAddress": "value".
Help would be really great.

Thanks

**Comment by muckisg** [comment]
Hi rolli,

i am using Fritzbox 7590. With the rest i can't really help you i guess. I have a lot of questions by now myself. 

E.g.: My mobile device is detectet by the Node-red script, but the web interface of the fritzbox says, that die device with that given MAC is not active, but it is with a different name and different MAC.

Very confusing,

Maurice
