### ISSUE TITLE
Fritz!Dect 500 Support

### ISSUE THREAD

**Issue by vonglahn** [bashGroup/node-red-contrib-fritz#62]
Hi there,

is the new Fritz!dect 500 supported? I can switch it on/off using "SetSwitch" but I don't know how to change the colour?

Any ideas are appreceated.

**Comment by mapero** [comment]
In general all provided functions of the fritzbox are supported. It is more or less a generic node that will support whatever the fritzbox is support over tr064.
From the official documentation, it does not seem that there is a correspoding service yet.
https://avm.de/fileadmin/user_upload/Global/Service/Schnittstellen/x_homeauto.pdf

**Comment by mapero** [comment]
So it seems like AVM developed some specific protocol for their new Home Automation stuff: https://avm.de/fileadmin/user_upload/Global/Service/Schnittstellen/AHA-HTTP-Interface.pdf

Since I don't have any of them here to test, no development of the interface is planed yet.

**Comment by mapero** [comment]
I send a support request to AVM regarding the future of the TR064 and AHA-HTTP Interface.
