### ISSUE TITLE
password only authentication does not work

### ISSUE THREAD

**Issue by lunarys** [bashGroup/node-red-contrib-fritz#63]
Authenticating with password only does not work for me. (FritzBox!7490, Fritz!OS 07.21).

I see this message in node-red: "Action failed with error: 401: Unauthorized"
And in the Fritz!Box log: Anmeldung einer App mit unbekanntem Anmeldenamen von IP-Adresse x.x.x.x gescheitert.

So I assume the username is expected to be empty, which is not allowed in the config node.

**Comment by claudiocerchia** [comment]
Use a random string for the _Username_ in your fritzbox-config node, e.g. _Username_ "doesnotexist"
Duplicate of #40

**Comment by lunarys** [comment]
I was convinced I tried that and it did not work 2 days ago. But now I checked again and it does work...
Sorry for the inconvenience.
