### ISSUE TITLE
Support new authentication

### ISSUE THREAD

**Issue by mapero** [bashGroup/node-red-contrib-fritz#64]
https://avm.de/fileadmin/user_upload/Global/Service/Schnittstellen/Empfehlungen%20zur%20Benutzerfu%CC%88hrung%20bei%20der%20Anmeldung%20an%20einer%20FRITZ%21Box_v1.1.pdf

**Comment by tstaddon** [comment]
I've upgraded my 7590 and Repeater 3000 to the latest firmware for both. Some API calls work with this, but actually the change is a "dummy" username no longer works.

On the beta firmware, a new username has been created for the default account, and it appears in "System / FRITZ!Box Users" / Login in to the Home Network" with the properties

-     created automatically
-     User to the FRITZ!Box password

I found all I needed to do to reinstate the connection was change the dummy username to this username in the config node.

**Comment by OEWEY** [comment]
> I've upgraded my 7590 and Repeater 3000 to the latest firmware for both. Some API calls work with this, but actually the change is a "dummy" username no longer works.
> 
> On the beta firmware, a new username has been created for the default account, and it appears in "System / FRITZ!Box Users" / Login in to the Home Network" with the properties
> 
>     * ```
>       created automatically
>       ```
> 
>     * ```
>       User to the FRITZ!Box password
>       ```
> 
> 
> I found all I needed to do to reinstate the connection was change the dummy username to this username in the config node.

Thank you for this hint! Saved me a lot of time :+1:

**Comment by mapero** [comment]
With 1.5.0 the users get fetched and provided as a selector
