### ISSUE TITLE
Calllist Limitation (Max Results) not working since FritzOS 7.21

### ISSUE THREAD

**Issue by mkcologne** [bashGroup/node-red-contrib-fritz#68]
Always get the complete list.
Suggestions?
Cheers - Michael

**Comment by mapero** [comment]
Maybe api changed. I will look into it coming week.

**Comment by mkcologne** [comment]
It started with 7.21 so an API change ist obvious.
Made a simple Workaround for myself.

[{"id":"3c0ec198.fdb816","type":"function","z":"bb630e24.dedb8","name":"ChangeMsgPayload","func":"msg.payload = msg.payload.Call;\n\nreturn msg;","outputs":1,"noerr":0,"initialize":"","finalize":"","x":480,"y":500,"wires":[["5a09148c.39d844"]]},{"id":"5a09148c.39d844","type":"function","z":"bb630e24.dedb8","name":"GetFirst6Items","func":"var n1 = msg.payload[0]\nvar n2 = msg.payload[1]\nvar n3 = msg.payload[2]\nvar n4 = msg.payload[3]\nvar n5 = msg.payload[4]\nvar n6 = msg.payload[5]\n\nmsg.payload = [n1,n2,n3,n4,n5,n6]\n\nreturn msg;\n","outputs":1,"noerr":0,"initialize":"","finalize":"","x":650,"y":420,"wires":[[]]}]
