### ISSUE TITLE
Failure X_AVM-DE_DialNumber / Error 500

### ISSUE THREAD

**Issue by Tobi266** [bashGroup/node-red-contrib-fritz#79]
Hi,
I'm using a 6490 Cable with FritzOS 7.24.
I want to start a phone call, triggered by an event.
Configuration of the Fritzbox-Node is:
![grafik](https://user-images.githubusercontent.com/84711635/119344954-91acbd80-bc98-11eb-855c-f2e107914de7.png)

The configuration of the box is working, for example it is possible to query the presence via "GetSpecificHostEntry".

Here the flow with the Debug-console an error:
![grafik](https://user-images.githubusercontent.com/84711635/119344835-6f1aa480-bc98-11eb-91f8-0891cdcc170e.png)

Thanks

**Comment by dos-ise** [comment]
Hi,

I am running  07.27 on my 5530 and have the same problems.

Best regards

**Comment by Tobi266** [comment]
I have updated my 6490 to Fritz!OS 7.27 but still the same problems...
regards

**Comment by Tobi266** [comment]
I've got a solution. You have to activate dial-help.
German user interface:
Telefonie -> Anrufe -> Reiter Wählhilfe -> Gerät auswählen
