### ISSUE TITLE
Lookup node shows "500: Internal Server Error"

### ISSUE THREAD

**Issue by foorschtbar** [bashGroup/node-red-contrib-fritz#81]
Plugin Version: 1.4.5
FB Version: Fritz!OS 07.21
FB Model: 6591 Cable

Without configure a Phonebook the lookup node find no entries. When i configure a phonebook in the node config, the node produces a "500: Internal Server Error" warning.

**Comment by pinguinpfleger** [comment]
As workaround you can use the id of the phonebook instead of the name.
0 for the first phonebook.

**Comment by foorschtbar** [comment]
> As workaround you can use the id of the phonebook instead of the name. 0 for the first phonebook.

Nice, that works. I use ID 1 for my iCloud phonebook. Thank u!
