### ISSUE TITLE
can be queried whether a VPN connection is active?

### ISSUE THREAD

**Issue by italschwob** [bashGroup/node-red-contrib-fritz#83]
I have a question, can be queried whether a VPN connection is active?
FB 7590
FB Firmware 7.28
could not find anything on this, have tried some without success.

**Comment by killerkeks2** [comment]
I suppose you want to get the state, if a VPN Connection is currently used or not, right?

I haven't done it myself, but i strongly think, this is possible:

Afaik a VPN Connection can be defined to be always on a static internal IP, e.g. 192.168.178.244 - so, in the end you just have to look for the presence of this device in your network - there should be no difference to a physical device, e.g. Smartphone. 
In the end you could also achieve this by regularly running broadcast pings in your network - thats the way i did it, before i found this project.

**Comment by mapero** [comment]
I believe VPN is one of the rare features that do not have a TR-064 API on the fritzbox. Did you contact AVM about this?
