### ISSUE TITLE
working example for setCallBarringEntry

### ISSUE THREAD

**Issue by averlon** [bashGroup/node-red-contrib-fritz#85]
Hi,
I have tried several options to use the service setCallBarringEntry but did not succeed.

Is there anywhere some example how the JSON-String should look like to get this service work?

The main problem is the array "number".
"_":"<value" is not accepted.

I have tried first to grab an existing number from Barring List and have constructed the JSON accordingly. But the "number" failed.

Any example welcome.

Thanks in advance
Kallewirsch

**Comment by averlon** [comment]
anyone here?

**Comment by averlon** [comment]
anyone here?

**Comment by killerkeks2** [comment]
I also wanna achieve, what you try. I added a separate Phonebook for Barrings and wanted to use the fritzbox-phonebook node to add new contacts to this phonebook. I can't seem to successfully add a contact via nodered. The missing documentation isn't helping any further.

In the tab "Rufsperre" (for readers, not sure about the exact name in english // smth with Barring maybe) you can then add the whole phonebook.

(nevertheless some functions of this project are amazing, e.g. the Callmonitor \o/)

**Comment by averlon** [comment]
@k1llerk3ks Projekt scheint verlassen zu sein! Aber ich habe aktuell auch nicht viel Zeit viele Dinge auszuprobieren.

**Comment by mapero** [comment]
So just to clarify. I am not paid for this project and I do this in my private time, which is currently limited.

The question you are asking is also not really related to this project but to the avm api. Please see https://avm.de/fileadmin/user_upload/Global/Service/Schnittstellen/x_contactSCPD.pdf for more information.

Based on some research you need to provide a PhonebookEntryData, which is basically XML:

```
<?xml version="1.0" encoding="utf-8"?><contact modified="0"><category>0</category><person><realName>Someone</realName></person><telephony nid="1"><number type="mobile" prio="1" id="0">+491234567890</number></telephony><services /><setup /></contact>
```

Find an example flow below:

```
[
    {
        "id": "aea994290c784806",
        "type": "tab",
        "label": "Set Call Barring Entry",
        "disabled": false,
        "info": "",
        "env": []
    },
    {
        "id": "4381b708e7a4efb7",
        "type": "fritzbox-in",
        "z": "aea994290c784806",
        "device": "c00721d0b2e6a7d7",
        "name": "",
        "service": "urn:dslforum-org:service:X_AVM-DE_OnTel:1",
        "action": "SetCallBarringEntry",
        "arguments": "{\n  \"NewPhonebookEntryData\": \"value\"\n}",
        "x": 570,
        "y": 200,
        "wires": [
            [
                "0b6d72f4faa09c0e"
            ]
        ]
    },
    {
        "id": "e5769b6addca6fe1",
        "type": "inject",
        "z": "aea994290c784806",
        "name": "SetCallBarringEntry",
        "props": [
            {
                "p": "payload"
            },
            {
                "p": "topic",
                "vt": "str"
            }
        ],
        "repeat": "",
        "crontab": "",
        "once": false,
        "onceDelay": 0.1,
        "topic": "",
        "payload": "{\"NewPhonebookEntryData\":\"<?xml version=\\\"1.0\\\" encoding=\\\"utf-8\\\"?><contact modified=\\\"0\\\"><category>0</category><person><realName>Someone</realName></person><telephony nid=\\\"1\\\"><number type=\\\"mobile\\\" prio=\\\"1\\\" id=\\\"0\\\">+491234567890</number></telephony><services /><setup /></contact>\"}",
        "payloadType": "json",
        "x": 330,
        "y": 200,
        "wires": [
            [
                "4381b708e7a4efb7"
            ]
        ]
    },
    {
        "id": "0b6d72f4faa09c0e",
        "type": "debug",
        "z": "aea994290c784806",
        "name": "debug 13",
        "active": true,
        "tosidebar": true,
        "console": false,
        "tostatus": false,
        "complete": "false",
        "statusVal": "",
        "statusType": "auto",
        "x": 780,
        "y": 200,
        "wires": []
    },
    {
        "id": "c00721d0b2e6a7d7",
        "type": "fritzbox-config",
        "name": "fritzbox",
        "host": "fritz.box",
        "port": "49000",
        "ssl": false,
        "user": "nodered"
    }
]
```

**Comment by averlon** [comment]
to understand the xml is not that easy. So I am happy to have an example. I will work on this!
Thanks for your time!
